{% set name = "sanic" %}
{% set version = "24.6.0" %}

package:
  name: sanic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e0841e2c8c28e68a0e6fc570c42aafbbe3b385d7141b9f96997d9d6c17d7afb

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - sanic = sanic.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=70.1
  run:
    - aiofiles >=0.6.0
    - httptools >=0.0.10
    - multidict >=5.0,<7.0
    - html5tagger >=1.2.1
    - tracerite >=1.0.0
    - typing_extensions >=4.4.0
    - python
    - sanic-routing >=23.12.0
    - ujson >=1.35  # [not win]
    - uvloop >=0.15.0  # [not win]
    - websockets >=10.0

test:
  imports:
    - sanic
    - sanic.mixins
  commands:
    - pip check
    - sanic --help
  requires:
    - pip

about:
  home: https://github.com/channelcat/sanic
  summary: Async Python 3.5+ web server that's written to go fast
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ahopkins
    - kszucs
    - nicoddemus
    - thewchan
