{% set version = "19.12.2" %}

package:
  name: sanic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sanic/sanic-{{ version }}.tar.gz
  sha256: 0760b568245917481d65456721c1c50ba72e53e15a191392277751377f2cf770

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - httptools >=0.0.10
    - ujson >=1.35  # [not win]
    - uvloop >=0.5.3  # [not win]    
    - aiofiles >=0.3.0
    - websockets >=7.0,<9.0
    - multidict >=4.0,<5.0
    - httpx ==0.9.3

test:
  imports:
    - sanic
    - sanic.app
    - sanic.blueprints
    - sanic.config
    - sanic.constants
    - sanic.cookies
    - sanic.exceptions
    - sanic.handlers
    - sanic.log
    - sanic.request
    - sanic.response
    - sanic.router
    - sanic.server
    - sanic.static
    - sanic.testing
    - sanic.views
    - sanic.websocket

about:
  home: https://github.com/channelcat/sanic
  summary: "Async Python 3.5+ web server that's written to go fast"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - nicoddemus
