{% set name = "sanic" %}
{% set version = "25.3.0" %}
{% set python_min = "3.9" %}

package:
  name: sanic
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 775d522001ec81f034ec8e4d7599e2175bfc097b8d57884f5e4c9322f5e369bb

build:
  number: 1
  noarch: python
  entry_points:
    - sanic = sanic.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=70.1
    - wheel
  run:
    - python >={{ python_min }}
    - sanic-routing >=23.12.0
    - httptools >=0.0.10
    - uvloop >=0.15.0  # [not win]
    - ujson >=1.35  # [not win]
    - aiofiles >=0.6.0
    - websockets >=10.0
    - multidict >=5.0,<7.0
    - html5tagger >=1.2.1
    - tracerite >=1.0.0
    - typing_extensions >=4.4.0
    - setuptools >=70.1

test:
  imports:
    - sanic
    - sanic.mixins
  commands:
    - pip check
    - sanic --help
  requires:
    - pip

about:
  home: https://github.com/channelcat/sanic
  summary: Async Python 3.9+ web server and web framework that's written to go fast.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ahopkins
    - kszucs
    - nicoddemus
    - thewchan
